### ISSUE TITLE
Get a live demo going

### ISSUE THREAD

**Issue by jacklightbody** [carleton-cs-energy-analytics/marthas-dashboard#1]

**Comment by jacklightbody** [comment]
As of 6567ebd, just need to deploy the flask app to the server

**Comment by jacklightbody** [comment]
Wsgi code is added in 2740f9e. Per Jeff, port 5000 isn't open on the firewall, so working on setting up mod_wsgi instead of opening up the port since we'd want to switch to mod_wsgi/apache at some point anyway

**Comment by dustinmichels** [comment]
This is working now, yeah? We could try to hook up continuous integration.

**Comment by jacklightbody** [comment]
Yup.
