### ISSUE TITLE
API calls are exclusive for timestamps, maybe shouldn't be?

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/marthas-dashboard#27]
Paging @jacklightbody .

It seems API calls exclude the given `start` and `end` timestamp, only capturing what's in between.

For example,

If my start date is the 17th, I can see the first point on the 18th, (at time 00:00)

![screen shot 2018-02-05 at 3 25 52 pm](https://user-images.githubusercontent.com/16504363/35829569-e7b66f70-0a88-11e8-8f3e-32bd8281d17d.png)

But if my start date is the 18th, the 00:00 time is excluded.

![screen shot 2018-02-05 at 3 26 05 pm](https://user-images.githubusercontent.com/16504363/35829571-eb05c338-0a88-11e8-8c5c-127146750353.png)

This seems a little odd to me, but maybe it's unavoidable? What do you think?

**Comment by jacklightbody** [comment]
Very easy to change either way, just need to change the inequalities in the SQL. I think between instinctively makes more sense to me when writing queries, but see your point from the user side.

**Comment by jacklightbody** [comment]
https://github.com/carleton-cs-energy-analytics/energy-analytics-comps/pull/45
