### ISSUE TITLE
Using Flask caching to reduce API calls?

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/marthas-dashboard#36]
I'm wondering if we can use Flask's caching abilities to save a DF, for a while, and then. Then we can check the cache for a particular DF before making a new API call. Maybe not super high priority but could be cool!

See: http://flask.pocoo.org/docs/0.12/patterns/caching/

**Comment by jacklightbody** [comment]
I'm not sure about the utility of this, as the cache would be most effective if we had lots of repeated queries which I'm not sure is how the dashboard would actually be used- seems unlikely for queries to be repeated in a short time span.

**Comment by dustinmichels** [comment]
I know we currently repeat some queries for the room compare tool-- first to make the table, then to run the anomaly detection tool (if checkbox checked), and then to make the graphs (after a table cell is clicked). I think table, anomaly tool, and graph make slightly different "values in range" queries, but repeat the same "points in building" and "rooms in building" queries. So maybe some caching could be useful here. But this could potentially be reworked in our code, without caching.

Also, if a user "toggles" between tools or points within a tool (looks at one, then looks at another, then goes back to the first), maybe it would be nice to have cached queries?

**Comment by jacklightbody** [comment]
Huh, I didn't know that, and that could definitely be useful then to cache points/buildings somehow. Though my sense is that sending the requests is not the time intensive part of the room comparison, but rather the k-means clustering, so caching requests might not result in much speedup. Is there a way that we could maybe cache the centroids to initialize as next time, so that k-means might take fewer iterations?

**Comment by jacklightbody** [comment]
So I hadn't realized that we were still doing requests for each buildings rooms and points. That is getting cached now, which should significantly speedup loading times for the dashboard. Could implement this for other things as well, but was a really good idea @dustinmichels

**Comment by dustinmichels** [comment]
Great start on this. I think I'll close this issue, but we'll include it other places if we can.
