### ISSUE TITLE
Fix date formatting on compare plot hover tool 

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/marthas-dashboard#37]
On the heatmap, hovering over a cell correctly displays the date as a date:

![screen shot 2018-02-19 at 10 42 59 am](https://user-images.githubusercontent.com/16504363/36388541-caa2a76c-1561-11e8-8142-dbe0f41641f9.png)

On the compare plot, not yet!

![screen shot 2018-02-19 at 10 43 05 am](https://user-images.githubusercontent.com/16504363/36388554-d5a02964-1561-11e8-89b5-832d1245ad0e.png)

**Comment by jacklightbody** [comment]
I can look into this
