### ISSUE TITLE
Every cell in room compare is an anomoly

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/marthas-dashboard#38]
Jon hooked up the anomaly detection tool to the room compare table, but alas, every point is flagged as an anomaly, perhaps because not enough data.

![screen shot 2018-02-19 at 10 45 24 am](https://user-images.githubusercontent.com/16504363/36388648-31624246-1562-11e8-8d04-0905463d11a6.png)

Perhaps we need to revert to a simpler highlighting system for this tool? One option is to include a checkbox in the menu with text like "highlight rooms where valve was over 80% on average throughout the day" and maybe make the 80% configurable? Thoughts?

**Comment by jacklightbody** [comment]
@carolynryan20 any idea what could be causing this?

**Comment by carolynryan20** [comment]
I'm planning on looking into it more today, might be something with one of the parameters that anomaly detection is taking in

**Comment by carolynryan20** [comment]
Yep! I think its 
```
size_threshold = df.shape[0] * 0.03
```
Where instead of df it should be pivoted_df

**Comment by bisilaj** [comment]
This should be resolved! See the open PR for the color-anomalous-points branch
