### ISSUE TITLE
Q: How alerts works

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/marthas-dashboard#39]
When I look at "alerts" I see a single table for the point "floatDEG F2" with a SD of 4.72. Just to clarify:
- Is this a point from any building? Or does it depend on the dropdown selections to the left, for the graph?
- Can we display tables for multiple points if multiple are above the SD cutoff?
- Also, what is the SD cutoff?

![screen shot 2018-02-19 at 10 52 39 am](https://user-images.githubusercontent.com/16504363/36388956-3059812e-1563-11e8-811a-7359be483262.png)

**Comment by jacklightbody** [comment]
This page shows alerts from the point/building combo that you choose in the dropdown to the left. I'm not sure what you mean in your second question- the sd cutoff is 2 standard deviations away from the mean for a point, and so is point specific- there's no real way to generalize it across different points.

**Comment by dustinmichels** [comment]
Ah, got it. It's highlighting the timestamps that are 2 SDs off. Thanks.
