### ISSUE TITLE
Select Buttons Javascript issue

### ISSUE THREAD

**Issue by jacklightbody** [carleton-cs-energy-analytics/marthas-dashboard#41]
Trying to select new points and times now gives a badly formatted url- see top toolbar in below.
<img width="805" alt="screen shot 2018-02-19 at 5 17 21 pm" src="https://user-images.githubusercontent.com/558566/36400820-eec68be0-1598-11e8-8770-3c6c1c3decdf.png">

History shows commits by @dustinmichels and @bisilaj to the comparison.js file- do either of you know what might be going on?

**Comment by dustinmichels** [comment]
Hmm. I can look into that.

**Comment by jacklightbody** [comment]
Awesome, thanks.

**Comment by jacklightbody** [comment]
Just figured it out- its just a namespace issue with the room-comparison script and the addInputUrl function. Fixed in my branch, will push in a bit
