### ISSUE TITLE
Adapt web app to updated database

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/marthas-dashboard#47]
Changes to database made all web pages come back empty. We should make sure all all defaults work, avoid hard coding IDs, and look out for other issues.

**Comment by dustinmichels** [comment]
I can work on fixing the room compare tools. It seems like the graphs are broken, and so are some of the dropdown selectors.

Can someone comment on how much the db is still in flux?

**Comment by carolynryan20** [comment]
@dustinmichels: Db should be mostly no longer in flux, we are still checking on a couple of the things we were worried about, but are hopeful that this version sticks

**Comment by dustinmichels** [comment]
Okay, great. Web app is working better than I thought.
