### ISSUE TITLE
Descriptions differ for points retrieved as "points" vs. "values"

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/marthas-dashboard#50]
When I query for a building's points, or values at a given time, it seems the results of both have a description attached, but the "points" have a longer descriptions than the "values", for things with the same point id. For example:

```python
# get points and vals
points = api.building_points('6')
vals = api.building_values_at_time('6', '2017-08-18 00:00:00')

vals.query('pointid==91')['description']
# --> 'Measurement of the Room Tempurature in Hulings (bio)'

points.query('id==91')['description']
# --> 'Measurement of the Room Tempurature'
```

Is that normal?

**Comment by jacklightbody** [comment]
So the api returns the description from the points table for the building_points query, but returns the description from the point types table for the building_values_at_time. Not sure why those are different, but that's what's going on under the hood.
